// Generated by gencpp from file serial_controllers/GPS.msg
// DO NOT EDIT!


#ifndef SERIAL_CONTROLLERS_MESSAGE_GPS_H
#define SERIAL_CONTROLLERS_MESSAGE_GPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_controllers
{
template <class ContainerAllocator>
struct GPS_
{
  typedef GPS_<ContainerAllocator> Type;

  GPS_()
    : lat(0.0)
    , lon(0.0)
    , angle(0.0)  {
    }
  GPS_(const ContainerAllocator& _alloc)
    : lat(0.0)
    , lon(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::serial_controllers::GPS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_controllers::GPS_<ContainerAllocator> const> ConstPtr;

}; // struct GPS_

typedef ::serial_controllers::GPS_<std::allocator<void> > GPS;

typedef boost::shared_ptr< ::serial_controllers::GPS > GPSPtr;
typedef boost::shared_ptr< ::serial_controllers::GPS const> GPSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_controllers::GPS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_controllers::GPS_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_controllers::GPS_<ContainerAllocator1> & lhs, const ::serial_controllers::GPS_<ContainerAllocator2> & rhs)
{
  return lhs.lat == rhs.lat &&
    lhs.lon == rhs.lon &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_controllers::GPS_<ContainerAllocator1> & lhs, const ::serial_controllers::GPS_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_controllers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::serial_controllers::GPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_controllers::GPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_controllers::GPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_controllers::GPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_controllers::GPS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_controllers::GPS_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_controllers::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0d1a5cb68bd3dce567ccfca35fbbd85";
  }

  static const char* value(const ::serial_controllers::GPS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0d1a5cb68bd3dceULL;
  static const uint64_t static_value2 = 0x567ccfca35fbbd85ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_controllers::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_controllers/GPS";
  }

  static const char* value(const ::serial_controllers::GPS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_controllers::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 lat\n"
"float64 lon\n"
"float64 angle\n"
;
  }

  static const char* value(const ::serial_controllers::GPS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_controllers::GPS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_controllers::GPS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_controllers::GPS_<ContainerAllocator>& v)
  {
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_CONTROLLERS_MESSAGE_GPS_H
