// Generated by gencpp from file serial_controllers/IMU_CMDResponse.msg
// DO NOT EDIT!


#ifndef SERIAL_CONTROLLERS_MESSAGE_IMU_CMDRESPONSE_H
#define SERIAL_CONTROLLERS_MESSAGE_IMU_CMDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_controllers
{
template <class ContainerAllocator>
struct IMU_CMDResponse_
{
  typedef IMU_CMDResponse_<ContainerAllocator> Type;

  IMU_CMDResponse_()
    : RX(false)  {
    }
  IMU_CMDResponse_(const ContainerAllocator& _alloc)
    : RX(false)  {
  (void)_alloc;
    }



   typedef uint8_t _RX_type;
  _RX_type RX;





  typedef boost::shared_ptr< ::serial_controllers::IMU_CMDResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_controllers::IMU_CMDResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IMU_CMDResponse_

typedef ::serial_controllers::IMU_CMDResponse_<std::allocator<void> > IMU_CMDResponse;

typedef boost::shared_ptr< ::serial_controllers::IMU_CMDResponse > IMU_CMDResponsePtr;
typedef boost::shared_ptr< ::serial_controllers::IMU_CMDResponse const> IMU_CMDResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_controllers::IMU_CMDResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_controllers::IMU_CMDResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_controllers::IMU_CMDResponse_<ContainerAllocator1> & lhs, const ::serial_controllers::IMU_CMDResponse_<ContainerAllocator2> & rhs)
{
  return lhs.RX == rhs.RX;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_controllers::IMU_CMDResponse_<ContainerAllocator1> & lhs, const ::serial_controllers::IMU_CMDResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_controllers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::serial_controllers::IMU_CMDResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_controllers::IMU_CMDResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_controllers::IMU_CMDResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_controllers::IMU_CMDResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_controllers::IMU_CMDResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_controllers::IMU_CMDResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_controllers::IMU_CMDResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b5b5e725f915f376c4c1cec2adbfcaa";
  }

  static const char* value(const ::serial_controllers::IMU_CMDResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b5b5e725f915f37ULL;
  static const uint64_t static_value2 = 0x6c4c1cec2adbfcaaULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_controllers::IMU_CMDResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_controllers/IMU_CMDResponse";
  }

  static const char* value(const ::serial_controllers::IMU_CMDResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_controllers::IMU_CMDResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool RX\n"
"\n"
;
  }

  static const char* value(const ::serial_controllers::IMU_CMDResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_controllers::IMU_CMDResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.RX);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IMU_CMDResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_controllers::IMU_CMDResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_controllers::IMU_CMDResponse_<ContainerAllocator>& v)
  {
    s << indent << "RX: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RX);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_CONTROLLERS_MESSAGE_IMU_CMDRESPONSE_H
