// Generated by gencpp from file serial_controllers/IMU_CMD.msg
// DO NOT EDIT!


#ifndef SERIAL_CONTROLLERS_MESSAGE_IMU_CMD_H
#define SERIAL_CONTROLLERS_MESSAGE_IMU_CMD_H

#include <ros/service_traits.h>


#include <serial_controllers/IMU_CMDRequest.h>
#include <serial_controllers/IMU_CMDResponse.h>


namespace serial_controllers
{

struct IMU_CMD
{

typedef IMU_CMDRequest Request;
typedef IMU_CMDResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IMU_CMD
} // namespace serial_controllers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::serial_controllers::IMU_CMD > {
  static const char* value()
  {
    return "3fdd3fa6d47360091f910c25807c31b8";
  }

  static const char* value(const ::serial_controllers::IMU_CMD&) { return value(); }
};

template<>
struct DataType< ::serial_controllers::IMU_CMD > {
  static const char* value()
  {
    return "serial_controllers/IMU_CMD";
  }

  static const char* value(const ::serial_controllers::IMU_CMD&) { return value(); }
};


// service_traits::MD5Sum< ::serial_controllers::IMU_CMDRequest> should match
// service_traits::MD5Sum< ::serial_controllers::IMU_CMD >
template<>
struct MD5Sum< ::serial_controllers::IMU_CMDRequest>
{
  static const char* value()
  {
    return MD5Sum< ::serial_controllers::IMU_CMD >::value();
  }
  static const char* value(const ::serial_controllers::IMU_CMDRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_controllers::IMU_CMDRequest> should match
// service_traits::DataType< ::serial_controllers::IMU_CMD >
template<>
struct DataType< ::serial_controllers::IMU_CMDRequest>
{
  static const char* value()
  {
    return DataType< ::serial_controllers::IMU_CMD >::value();
  }
  static const char* value(const ::serial_controllers::IMU_CMDRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::serial_controllers::IMU_CMDResponse> should match
// service_traits::MD5Sum< ::serial_controllers::IMU_CMD >
template<>
struct MD5Sum< ::serial_controllers::IMU_CMDResponse>
{
  static const char* value()
  {
    return MD5Sum< ::serial_controllers::IMU_CMD >::value();
  }
  static const char* value(const ::serial_controllers::IMU_CMDResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_controllers::IMU_CMDResponse> should match
// service_traits::DataType< ::serial_controllers::IMU_CMD >
template<>
struct DataType< ::serial_controllers::IMU_CMDResponse>
{
  static const char* value()
  {
    return DataType< ::serial_controllers::IMU_CMD >::value();
  }
  static const char* value(const ::serial_controllers::IMU_CMDResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERIAL_CONTROLLERS_MESSAGE_IMU_CMD_H
